import type { Category, Enquiry, Location, MaterialListing, PlatformStats, Requirement, Supplier } from "./types"

// Real, licensed Unsplash photography, addressed by verified photo IDs —
// swap for the client's own product/warehouse photography when available.
const photo = (id: string, w = 900, h = 700) =>
  `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&auto=format&q=80`

// A small pool of verified, on-theme photo IDs per category, reused across
// the category card and that category's product listings for variety.
export const categoryPhotoIds: Record<string, string[]> = {
  tiles: [
    "photo-1523350165414-082d792c4bcc",
    "photo-1551893478-d726eaf0442c",
    "photo-1613124152913-c180d8c1d740",
    "photo-1541471943749-e5976783f6c3",
  ],
  furniture: [
    "photo-1667584523543-d1d9cc828a15",
    "photo-1759722665629-29df6ee4f9a5",
    "photo-1758957701419-2c6e266f7988",
  ],
  sanitaryware: [
    "photo-1542855368-ca6ea825bca2",
    "photo-1635286771551-9d7241ce7811",
    "photo-1609208522221-bd6b667fb671",
  ],
  plywood: ["photo-1604916932991-eeb07b40bdcf", "photo-1601391548091-de4ff62ee29c", "photo-1568023905551-0f6247c134f3"],
  "interior-walls": [
    "photo-1701421052582-9f6935aff566",
    "photo-1701421048959-1e8108509834",
    "photo-1722109997425-40f920848aed",
  ],
  panels: ["photo-1700809887581-c41c239e808e", "photo-1675528030748-d463ab87e8d5", "photo-1701422052205-f75bbc1be612"],
  flooring: [
    "photo-1585128792020-803d29415281",
    "photo-1573869908170-64b53a60d8da",
    "photo-1598718544285-7180f670198b",
  ],
  bathroom: [
    "photo-1650894622076-e09ab837c502",
    "photo-1643949700215-e61cdca053f7",
    "photo-1642755622932-d1e0cb783dc5",
  ],
  lighting: ["photo-1540932239986-30128078f3c5", "photo-1515948725-edac7b5bb0fc", "photo-1581784878214-8d5596b98a01"],
  hardware: [
    "photo-1581783898377-1c85bf937427",
    "photo-1581166397057-235af2b3c6dd",
    "photo-1611288875785-f62fb9b044a7",
  ],
  "building-materials": [
    "photo-1560435650-7ec2e17ba926",
    "photo-1666219462105-2909c2d72d01",
    "photo-1669170930713-f7c778496177",
  ],
  "home-improvement": [
    "photo-1645651964715-d200ce0939cc",
    "photo-1606676539940-12768ce0e762",
    "photo-1540103711724-ebf833bde8d1",
  ],
  "commercial-interiors": [
    "photo-1715593949273-09009558300a",
    "photo-1706074797611-a02f9ed06439",
    "photo-1646153114001-495dfb56506d",
  ],
  electronics: [
    "photo-1635335874521-7987db781153",
    "photo-1601462904263-f2fa0c851cb9",
    "photo-1473831818960-c89731aabc3e",
  ],
}

function categoryImages(categoryId: string, w = 900, h = 700): string[] {
  return (categoryPhotoIds[categoryId] ?? categoryPhotoIds.tiles ?? []).map((id) => photo(id, w, h))
}

function categoryCover(categoryId: string): string {
  return categoryImages(categoryId)[0] ?? photo("photo-1523350165414-082d792c4bcc")
}

// Initials-based placeholder logos — swap for real supplier logos once
// suppliers upload their own branding.
const avatar = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=173C8A&color=FFFFFF&size=200&bold=true&font-size=0.36`

export const categories: Category[] = [
  {
    id: "tiles",
    slug: "tiles",
    name: "Tiles",
    descriptor: "Premium surfaces. Exceptional value.",
    listingCount: 1840,
    imageUrl: categoryCover("tiles"),
  },
  {
    id: "furniture",
    slug: "furniture",
    name: "Furniture",
    descriptor: "Commercial & residential pieces.",
    listingCount: 1260,
    imageUrl: categoryCover("furniture"),
  },
  {
    id: "sanitaryware",
    slug: "sanitaryware",
    name: "Sanitaryware",
    descriptor: "Fixtures at a fraction of the cost.",
    listingCount: 640,
    imageUrl: categoryCover("sanitaryware"),
  },
  {
    id: "plywood",
    slug: "plywood",
    name: "Plywood",
    descriptor: "Structural boards, ready to move.",
    listingCount: 780,
    imageUrl: categoryCover("plywood"),
  },
  {
    id: "interior-walls",
    slug: "interior-walls",
    name: "Interior Walls",
    descriptor: "Wall finishes and cladding.",
    listingCount: 410,
    imageUrl: categoryCover("interior-walls"),
  },
  {
    id: "panels",
    slug: "panels",
    name: "Panels",
    descriptor: "Decorative & acoustic panelling.",
    listingCount: 305,
    imageUrl: categoryCover("panels"),
  },
  {
    id: "flooring",
    slug: "flooring",
    name: "Flooring",
    descriptor: "Laminate, vinyl and stone flooring.",
    listingCount: 690,
    imageUrl: categoryCover("flooring"),
  },
  {
    id: "bathroom",
    slug: "bathroom",
    name: "Bathroom",
    descriptor: "Complete bathroom solutions.",
    listingCount: 520,
    imageUrl: categoryCover("bathroom"),
  },
  {
    id: "lighting",
    slug: "lighting",
    name: "Lighting",
    descriptor: "Fixtures for every space.",
    listingCount: 460,
    imageUrl: categoryCover("lighting"),
  },
  {
    id: "hardware",
    slug: "hardware",
    name: "Hardware",
    descriptor: "Fittings, fasteners and fixtures.",
    listingCount: 590,
    imageUrl: categoryCover("hardware"),
  },
  {
    id: "building-materials",
    slug: "building-materials",
    name: "Building Materials",
    descriptor: "Core construction supplies.",
    listingCount: 730,
    imageUrl: categoryCover("building-materials"),
  },
  {
    id: "home-improvement",
    slug: "home-improvement",
    name: "Home Improvement",
    descriptor: "Everyday upgrade essentials.",
    listingCount: 385,
    imageUrl: categoryCover("home-improvement"),
  },
  {
    id: "commercial-interiors",
    slug: "commercial-interiors",
    name: "Commercial Interiors",
    descriptor: "Office & retail fit-out materials.",
    listingCount: 268,
    imageUrl: categoryCover("commercial-interiors"),
  },
  {
    id: "electronics",
    slug: "electronics",
    name: "Electronics & Electricals",
    descriptor: "Wiring, switchgear, fans and smart fittings.",
    listingCount: 540,
    imageUrl: categoryCover("electronics"),
    subcategories: [
      "Switches & Sockets",
      "MCBs & Distribution Boards",
      "Wires & Cables",
      "Fans & Ventilation",
      "LED Drivers & Controls",
      "Smart Home Devices",
      "Water Heaters & Geysers",
      "CCTV & Security",
    ],
    specFields: [
      "Brand",
      "Model number",
      "Voltage / rating",
      "Warranty remaining",
      "Certification (ISI / BIS)",
      "Working condition",
    ],
  },
]

export const locations: Location[] = [
  {
    id: "delhi-ncr",
    city: "Delhi NCR",
    state: "Delhi",
    region: "North",
    country: "India",
    listingCount: 2140,
  },
  {
    id: "mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    region: "West",
    country: "India",
    listingCount: 1860,
  },
  {
    id: "bangalore",
    city: "Bangalore",
    state: "Karnataka",
    region: "South",
    country: "India",
    listingCount: 1420,
  },
  {
    id: "hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    region: "South",
    country: "India",
    listingCount: 980,
  },
  {
    id: "pune",
    city: "Pune",
    state: "Maharashtra",
    region: "West",
    country: "India",
    listingCount: 860,
  },
  {
    id: "jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    region: "North",
    country: "India",
    listingCount: 520,
  },
  {
    id: "ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    region: "West",
    country: "India",
    listingCount: 640,
  },
  {
    id: "lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    region: "North",
    country: "India",
    listingCount: 390,
  },
  {
    id: "meerut",
    city: "Meerut",
    state: "Uttar Pradesh",
    region: "North",
    country: "India",
    listingCount: 210,
  },
  {
    id: "gurugram",
    city: "Gurugram",
    state: "Haryana",
    region: "North",
    country: "India",
    listingCount: 970,
  },
  {
    id: "noida",
    city: "Noida",
    state: "Uttar Pradesh",
    region: "North",
    country: "India",
    listingCount: 705,
  },
]

export const suppliers: Supplier[] = [
  {
    id: "shreeji-tile-distributors",
    slug: "shreeji-tile-distributors",
    name: "Shreeji Tile Distributors",
    logoUrl: avatar("Shreeji Tile Distributors"),
    verified: true,
    location: "Gurugram, Haryana",
    categories: ["Tiles", "Flooring"],
    activeListings: 128,
    availableInventoryUnits: 84000,
    yearsActive: 14,
    responseRate: 96,
    rating: 4.7,
    reviewCount: 214,
    memberSince: "2021-02-10",
    description:
      "Surplus and overstock tile distributor sourcing from manufacturers across Morbi and Kajaria network partners.",
  },
  {
    id: "urban-nest-furniture",
    slug: "urban-nest-furniture",
    name: "Urban Nest Furniture Traders",
    logoUrl: avatar("Urban Nest Furniture Traders"),
    verified: true,
    location: "Mumbai, Maharashtra",
    categories: ["Furniture", "Commercial Interiors"],
    activeListings: 96,
    availableInventoryUnits: 5400,
    yearsActive: 9,
    responseRate: 93,
    rating: 4.6,
    reviewCount: 156,
    memberSince: "2020-06-18",
  },
  {
    id: "aquafit-sanitaryware",
    slug: "aquafit-sanitaryware",
    name: "AquaFit Sanitaryware Co.",
    logoUrl: avatar("AquaFit Sanitaryware"),
    verified: true,
    location: "Ahmedabad, Gujarat",
    categories: ["Sanitaryware", "Bathroom"],
    activeListings: 74,
    availableInventoryUnits: 3200,
    yearsActive: 11,
    responseRate: 91,
    rating: 4.5,
    reviewCount: 98,
    memberSince: "2021-09-04",
  },
  {
    id: "timberline-ply-traders",
    slug: "timberline-ply-traders",
    name: "Timberline Ply Traders",
    logoUrl: avatar("Timberline Ply Traders"),
    verified: true,
    location: "Bangalore, Karnataka",
    categories: ["Plywood", "Interior Walls"],
    activeListings: 61,
    availableInventoryUnits: 18400,
    yearsActive: 7,
    responseRate: 97,
    rating: 4.8,
    reviewCount: 132,
    memberSince: "2022-01-22",
  },
  {
    id: "wallcraft-interiors",
    slug: "wallcraft-interiors",
    name: "WallCraft Interiors",
    logoUrl: avatar("WallCraft Interiors"),
    verified: false,
    location: "Pune, Maharashtra",
    categories: ["Panels", "Interior Walls"],
    activeListings: 38,
    availableInventoryUnits: 2100,
    yearsActive: 5,
    responseRate: 88,
    rating: 4.3,
    reviewCount: 47,
    memberSince: "2023-03-30",
  },
  {
    id: "buildright-hardware",
    slug: "buildright-hardware",
    name: "BuildRight Hardware & Materials",
    logoUrl: avatar("BuildRight Hardware"),
    verified: true,
    location: "Delhi NCR, Delhi",
    categories: ["Hardware", "Building Materials"],
    activeListings: 143,
    availableInventoryUnits: 26700,
    yearsActive: 16,
    responseRate: 95,
    rating: 4.7,
    reviewCount: 260,
    memberSince: "2019-11-05",
  },
]

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()
}

export const listings: MaterialListing[] = [
  {
    id: "lot-marble-tile-2400",
    slug: "premium-marble-finish-tile-2400-sqft",
    title: "Premium Marble Finish Tile",
    brand: "Kajaria",
    categoryId: "tiles",
    subcategory: "Floor Tiles",
    condition: "surplus",
    images: categoryImages("tiles"),
    quantity: 2400,
    unit: "sq-ft",
    minOrderQuantity: 200,
    locationId: "gurugram",
    supplierId: "shreeji-tile-distributors",
    dealType: "buy-now",
    marketValue: 180000,
    price: 98000,
    logisticsMethods: ["transport-arranged", "self-pickup"],
    description:
      "Surplus batch of premium marble-finish vitrified tiles from a completed commercial project. Full batch from a single production run for consistent shade matching.",
    conditionNotes: "Surplus stock, factory-sealed boxes, no visible defects.",
    specifications: [
      { label: "Size", value: "800mm x 1600mm" },
      { label: "Finish", value: "Polished Marble" },
      { label: "Thickness", value: "9mm" },
      { label: "Application", value: "Flooring, Commercial & Residential" },
    ],
    dimensions: "800mm x 1600mm",
    material: "Vitrified Ceramic",
    finish: "Polished",
    color: "Ivory White",
    packaging: "Factory-sealed cartons, 2 tiles/box",
    dateAdded: daysAgo(2),
    featured: true,
    wishlistCount: 62,
  },
  {
    id: "lot-office-workstations-40",
    slug: "modular-office-workstations-40-sets",
    title: "Modular Office Workstations",
    brand: "Featherlite",
    categoryId: "furniture",
    subcategory: "Office Furniture",
    condition: "excess",
    images: categoryImages("furniture"),
    quantity: 40,
    unit: "set",
    minOrderQuantity: 5,
    locationId: "mumbai",
    supplierId: "urban-nest-furniture",
    dealType: "request-quote",
    marketValue: 1200000,
    price: 560000,
    logisticsMethods: ["transport-arranged"],
    description:
      "Excess inventory of 4-seater modular workstation sets from a cancelled corporate fit-out order. Includes desks, partitions and cable management.",
    specifications: [
      { label: "Configuration", value: "4-Seater Cluster" },
      { label: "Material", value: "Engineered Wood + Steel Frame" },
      {
        label: "Warranty",
        value: "Manufacturer warranty voided — resale stock",
      },
    ],
    material: "Engineered Wood, Powder-Coated Steel",
    color: "Walnut / Grey",
    packaging: "Flat-packed, assembly required",
    dateAdded: daysAgo(6),
    featured: true,
    wishlistCount: 34,
  },
  {
    id: "lot-sanitaryware-wc-120",
    slug: "wall-mounted-wc-units-120-pieces",
    title: "Wall-Mounted WC Units",
    brand: "Hindware",
    categoryId: "sanitaryware",
    subcategory: "Water Closets",
    condition: "overstock",
    images: categoryImages("sanitaryware").slice(0, 2),
    quantity: 120,
    unit: "piece",
    minOrderQuantity: 10,
    locationId: "ahmedabad",
    supplierId: "aquafit-sanitaryware",
    dealType: "buy-now",
    marketValue: 960000,
    price: 528000,
    logisticsMethods: ["transport-arranged", "self-pickup"],
    description:
      "Overstock batch of wall-mounted WC units from a discontinued finish line. New, unused, with fittings included.",
    specifications: [
      { label: "Mounting", value: "Wall-Hung" },
      { label: "Flush Type", value: "Dual Flush" },
      { label: "Finish", value: "Gloss White" },
    ],
    material: "Vitreous China",
    color: "Gloss White",
    packaging: "Individually boxed",
    dateAdded: daysAgo(4),
    featured: true,
    wishlistCount: 28,
  },
  {
    id: "lot-plywood-bwp-800",
    slug: "bwp-grade-plywood-sheets-800-sheets",
    title: "BWP Grade Plywood Sheets",
    brand: "CenturyPly",
    categoryId: "plywood",
    subcategory: "Structural Plywood",
    condition: "factory-stock",
    images: categoryImages("plywood").slice(0, 2),
    quantity: 800,
    unit: "sheet",
    minOrderQuantity: 50,
    locationId: "bangalore",
    supplierId: "timberline-ply-traders",
    dealType: "bulk-deal",
    marketValue: 2400000,
    price: 1520000,
    logisticsMethods: ["transport-arranged", "freight"],
    description:
      "Factory-fresh BWP grade plywood sheets, boiling water proof, ready for immediate dispatch in bulk quantities.",
    specifications: [
      { label: "Size", value: "8ft x 4ft" },
      { label: "Thickness", value: "19mm" },
      { label: "Grade", value: "BWP (IS:710)" },
    ],
    dimensions: "8ft x 4ft x 19mm",
    material: "Hardwood Plywood",
    packaging: "Bundled, 10 sheets/bundle",
    dateAdded: daysAgo(1),
    featured: true,
    wishlistCount: 51,
  },
  {
    id: "lot-wall-panels-1500",
    slug: "acoustic-wall-panels-1500-sqft",
    title: "Acoustic Wall Panels",
    brand: "Armstrong",
    categoryId: "panels",
    subcategory: "Acoustic Panelling",
    condition: "display-stock",
    images: categoryImages("panels").slice(0, 2),
    quantity: 1500,
    unit: "sq-ft",
    minOrderQuantity: 100,
    locationId: "pune",
    supplierId: "wallcraft-interiors",
    dealType: "request-quote",
    marketValue: 675000,
    price: 385000,
    logisticsMethods: ["self-pickup", "local-delivery"],
    description:
      "Ex-display acoustic wall panelling from a showroom refit. Minor handling marks on select pieces, otherwise fully functional.",
    specifications: [
      { label: "NRC Rating", value: "0.85" },
      { label: "Thickness", value: "25mm" },
      { label: "Application", value: "Offices, Auditoriums, Studios" },
    ],
    material: "Fabric-Wrapped Fibreglass",
    finish: "Matte Fabric",
    dateAdded: daysAgo(8),
    wishlistCount: 19,
  },
  {
    id: "lot-vinyl-flooring-3000",
    slug: "commercial-vinyl-flooring-3000-sqft",
    title: "Commercial Vinyl Flooring Rolls",
    brand: "Armstrong Flooring",
    categoryId: "flooring",
    subcategory: "Vinyl Flooring",
    condition: "clearance",
    images: categoryImages("flooring").slice(0, 2),
    quantity: 3000,
    unit: "sq-ft",
    minOrderQuantity: 300,
    locationId: "noida",
    supplierId: "shreeji-tile-distributors",
    dealType: "buy-now",
    marketValue: 540000,
    price: 264000,
    logisticsMethods: ["transport-arranged", "freight"],
    description:
      "Clearance stock of commercial-grade vinyl flooring rolls, discontinued colourway. Ideal for offices, retail and healthcare spaces.",
    specifications: [
      { label: "Thickness", value: "2mm" },
      { label: "Wear Layer", value: "0.5mm" },
      { label: "Roll Width", value: "2m" },
    ],
    material: "Luxury Vinyl",
    color: "Slate Grey",
    packaging: "Rolled, 50 sq.ft/roll",
    dateAdded: daysAgo(3),
    wishlistCount: 22,
  },
  {
    id: "lot-led-panel-lights-600",
    slug: "led-panel-lights-600-units",
    title: "LED Panel Lights",
    brand: "Philips",
    categoryId: "lighting",
    subcategory: "Commercial Lighting",
    condition: "overstock",
    images: categoryImages("lighting").slice(0, 2),
    quantity: 600,
    unit: "piece",
    minOrderQuantity: 25,
    locationId: "delhi-ncr",
    supplierId: "buildright-hardware",
    dealType: "buy-now",
    marketValue: 900000,
    price: 468000,
    logisticsMethods: ["transport-arranged", "self-pickup"],
    description:
      "Overstock LED panel lights from a bulk import order. New and boxed, suitable for office and retail fit-outs.",
    specifications: [
      { label: "Size", value: "2ft x 2ft" },
      { label: "Wattage", value: "36W" },
      { label: "Colour Temp", value: "6500K Cool Daylight" },
    ],
    packaging: "Individually boxed",
    dateAdded: daysAgo(5),
    wishlistCount: 17,
  },
  {
    id: "lot-hardware-fittings-mixed",
    slug: "mixed-cabinet-hardware-fittings-bulk-lot",
    title: "Mixed Cabinet Hardware & Fittings",
    brand: "Hettich",
    categoryId: "hardware",
    subcategory: "Cabinet Hardware",
    condition: "excess",
    images: categoryImages("hardware").slice(0, 2),
    quantity: 4200,
    unit: "piece",
    minOrderQuantity: 200,
    locationId: "delhi-ncr",
    supplierId: "buildright-hardware",
    dealType: "bulk-deal",
    marketValue: 630000,
    price: 315000,
    logisticsMethods: ["transport-arranged", "freight"],
    description:
      "Excess inventory of soft-close hinges, drawer channels and cabinet handles from a modular kitchen manufacturer.",
    specifications: [
      { label: "Contents", value: "Hinges, Channels, Handles" },
      { label: "Finish", value: "Matte Steel / Chrome" },
    ],
    packaging: "Bulk cartons",
    dateAdded: daysAgo(9),
    wishlistCount: 12,
  },
  {
    id: "lot-cement-boards-500",
    slug: "fibre-cement-boards-500-sheets",
    title: "Fibre Cement Boards",
    brand: "Everest",
    categoryId: "building-materials",
    subcategory: "Structural Boards",
    condition: "factory-stock",
    images: categoryImages("building-materials").slice(0, 2),
    quantity: 500,
    unit: "sheet",
    minOrderQuantity: 50,
    locationId: "hyderabad",
    supplierId: "timberline-ply-traders",
    dealType: "contact-supplier",
    marketValue: 750000,
    price: 480000,
    logisticsMethods: ["freight", "transport-arranged"],
    description:
      "Factory stock fibre cement boards suited for partition walls, ceilings and exterior cladding applications.",
    specifications: [
      { label: "Size", value: "8ft x 4ft" },
      { label: "Thickness", value: "12mm" },
    ],
    dimensions: "8ft x 4ft x 12mm",
    material: "Fibre Cement",
    dateAdded: daysAgo(7),
    wishlistCount: 9,
  },
  {
    id: "lot-modular-kitchen-units-15",
    slug: "modular-kitchen-cabinet-sets-15-units",
    title: "Modular Kitchen Cabinet Sets",
    brand: "Sleek",
    categoryId: "home-improvement",
    subcategory: "Modular Kitchens",
    condition: "customer-return",
    images: categoryImages("home-improvement").slice(0, 2),
    quantity: 15,
    unit: "set",
    minOrderQuantity: 1,
    locationId: "lucknow",
    supplierId: "urban-nest-furniture",
    dealType: "request-quote",
    marketValue: 1875000,
    price: 1125000,
    logisticsMethods: ["transport-arranged"],
    description:
      "Customer-return modular kitchen sets, cancelled after order changes. Complete cabinet sets with minor cosmetic wear on select units.",
    specifications: [
      { label: "Layout", value: "L-Shaped, 10ft x 8ft" },
      { label: "Finish", value: "High Gloss Laminate" },
    ],
    material: "MDF with Laminate Finish",
    color: "Matte White / Walnut",
    dateAdded: daysAgo(11),
    wishlistCount: 15,
  },
  {
    id: "lot-retail-fixtures-30",
    slug: "retail-display-fixtures-30-units",
    title: "Retail Display Fixtures",
    brand: "Mixed Brands",
    categoryId: "commercial-interiors",
    subcategory: "Retail Fit-Out",
    condition: "display-stock",
    images: categoryImages("commercial-interiors").slice(0, 2),
    quantity: 30,
    unit: "piece",
    minOrderQuantity: 2,
    locationId: "jaipur",
    supplierId: "wallcraft-interiors",
    dealType: "contact-supplier",
    marketValue: 450000,
    price: 210000,
    logisticsMethods: ["self-pickup", "local-delivery"],
    description:
      "Ex-showroom retail display fixtures and gondola units from a store renovation. Good condition, ready for reuse.",
    specifications: [
      { label: "Type", value: "Gondola & Wall Units" },
      { label: "Material", value: "Powder-Coated Steel + MDF" },
    ],
    dateAdded: daysAgo(13),
    wishlistCount: 7,
  },
  {
    id: "lot-bathroom-fittings-set-80",
    slug: "premium-bathroom-fitting-sets-80-sets",
    title: "Premium Bathroom Fitting Sets",
    brand: "Jaquar",
    categoryId: "bathroom",
    subcategory: "Bath Fittings",
    condition: "discontinued",
    images: categoryImages("bathroom").slice(0, 2),
    quantity: 80,
    unit: "set",
    minOrderQuantity: 5,
    locationId: "gurugram",
    supplierId: "aquafit-sanitaryware",
    dealType: "buy-now",
    marketValue: 960000,
    price: 552000,
    logisticsMethods: ["transport-arranged", "self-pickup"],
    description:
      "Discontinued finish bathroom fitting sets — taps, showers and accessories. New in box, full sets only.",
    specifications: [
      { label: "Contents", value: "Basin Mixer, Shower, Accessories" },
      { label: "Finish", value: "Matte Black" },
    ],
    material: "Brass",
    color: "Matte Black",
    packaging: "Boxed sets",
    dateAdded: daysAgo(4),
    featured: true,
    wishlistCount: 41,
  },
  {
    id: "lot-mcb-boards-300",
    slug: "mcb-distribution-boards-300-pieces",
    title: "MCB & Distribution Boards",
    brand: "Legrand",
    categoryId: "electronics",
    subcategory: "MCBs & Distribution Boards",
    condition: "overstock",
    images: categoryImages("electronics"),
    quantity: 300,
    unit: "piece",
    minOrderQuantity: 20,
    locationId: "noida",
    supplierId: "buildright-hardware",
    dealType: "request-quote",
    marketValue: 690000,
    price: 372000,
    logisticsMethods: ["transport-arranged", "self-pickup"],
    description:
      "Overstock ISI-certified MCBs and 8-way distribution boards from a cancelled commercial electrification order. New, sealed cartons.",
    specifications: [
      { label: "Rating", value: "6A – 63A, 240V" },
      { label: "Certification", value: "ISI / BIS" },
      { label: "Warranty", value: "Manufacturer warranty transferable" },
    ],
    packaging: "Sealed cartons of 12",
    dateAdded: daysAgo(3),
    wishlistCount: 11,
  },
]

export const platformStats: PlatformStats = {
  inventoryValue: 420000000,
  activeListings: 9600,
  verifiedSuppliers: 380,
  categories: 35,
  cities: 42,
}

export const heroTrustIndicators = [
  "Authentic Surplus Stock",
  "Better Value",
  "Trusted Sourcing",
  "Pan-India Procurement",
  "Sustainable Choice",
]

export const popularSearches = [
  "Marble tiles Gurugram",
  "Commercial furniture bulk",
  "Sanitaryware overstock",
  "BWP plywood sheets",
  "Wall panels Pune",
]

export const trendingMaterials = [
  "Vitrified floor tiles",
  "Modular office furniture",
  "LED panel lights",
  "Fibre cement boards",
]

export const faqs = [
  {
    q: "What does 'surplus' mean on MaalGodaam?",
    a: "Surplus covers excess, overstock, discontinued, clearance, customer-return, display-stock and factory-stock material — quality inventory that a supplier needs to move, listed clearly with its condition.",
  },
  {
    q: "How is pricing different from retail?",
    a: "Every listing shows the estimated market value alongside the MaalGodaam price, so you can see the savings before you buy or request a quote.",
  },
  {
    q: "What's the difference between Buy Now, Request Quote and Bulk Deal?",
    a: "Buy Now lists a fixed price you can purchase directly. Request Quote lets you ask a supplier for pricing on your specific quantity. Bulk Deal is for large-volume purchases that typically involve negotiation.",
  },
  {
    q: "How do I post a bulk requirement?",
    a: "Use 'Post Your Requirement' to tell us the material, quantity, location and budget you need — our sourcing network helps match you with suppliers.",
  },
  {
    q: "How are suppliers verified?",
    a: "Suppliers go through a review of their business and listing details before they can publish inventory on the platform.",
  },
  {
    q: "How do I sell my surplus material?",
    a: "Go to 'Sell Your Surplus', submit your inventory details, and our team verifies the listing before it goes live to buyers across India.",
  },
]

export function getListingById(id: string) {
  return listings.find((l) => l.id === id || l.slug === id)
}

export function getSupplierById(id: string) {
  return suppliers.find((s) => s.id === id || s.slug === id)
}

export function getCategoryById(id: string) {
  return categories.find((c) => c.id === id || c.slug === id)
}

export function getLocationById(id: string) {
  return locations.find((l) => l.id === id)
}

export function getRelatedListings(listing: MaterialListing, limit = 4) {
  return listings.filter((l) => l.id !== listing.id && l.categoryId === listing.categoryId).slice(0, limit)
}

export const myRequirements: Requirement[] = [
  {
    id: "req-1",
    material: "Vitrified floor tiles, 600x600mm",
    categoryId: "tiles",
    quantity: 4000,
    unit: "sq-ft",
    preferredLocation: "Noida",
    budget: "₹1,50,000 – ₹2,00,000",
    requiredBy: daysAgo(-12),
    status: "matching",
    createdAt: daysAgo(3),
  },
  {
    id: "req-2",
    material: "Modular office workstations",
    categoryId: "furniture",
    quantity: 20,
    unit: "set",
    preferredLocation: "Bangalore",
    status: "open",
    createdAt: daysAgo(6),
  },
]

export const myEnquiries: Enquiry[] = [
  {
    id: "enq-1",
    listingId: "lot-marble-tile-2400",
    supplierId: "shreeji-tile-distributors",
    type: "quote",
    buyerName: "You",
    message: "Interested in the full 2,400 sq.ft lot — please confirm delivery timeline.",
    status: "responded",
    createdAt: daysAgo(2),
  },
  {
    id: "enq-2",
    listingId: "lot-plywood-bwp-800",
    supplierId: "timberline-ply-traders",
    type: "bulk",
    buyerName: "You",
    status: "pending",
    createdAt: daysAgo(1),
  },
]
